setuped for criterion unit testing
narval-xyz/armory pull request #523
Opened 2024-08-27 16:41 UTC by Ptroger

2024-09-17 21:41 UTC, mattschoch requested changes
Looks great, couple small things & 2 tests are failing when I run them; can you check and see if they're failing for you (if not, then that's also an issue if they're intermittently failing)

Then, maybe here or maybe as a separate scope, i do think we should move this whole e2e test suite out of the armory-sdk package into a `e2e-tests` package, since it doesn't have any direct coupling to the codebase; it's a gray-box e2e test suite.

2024-09-17 21:41 UTC, mattschoch commented on packages/policy-engine-shared/src/lib/dev.fixture.ts
> +  Antoine: '0x3e4989d1d83959d9dbec1f14bfb0685cfd15f4fd5037dc6e37e88e01838aef65',
Alice, Bob, Carol, Dave are A, B, C, D...using Antoine breaks the pattern 😉

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/default.json
All of these json files are test files, right? These shouldn't be in a top-level directory; they should be inside a `__test__` dir to make it clear these are not part of the SDK itself.

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/default.json
> +  ],
Why do you have the `managed` ones in `addressBook`? In practice, managed Accounts don't get duplicated into Address Book explicitly, they're inferred by Rego at runtime. I suggest using that pattern in the tests so that it would catch an error where the account isn't being looked up correctly if it's not also in the address book.

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/fixture.json
What is `fixture.json` versus `default.json`?

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/test.default.json
What is test.default.json vs default.json?

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/fixture.json
I don't think I see fixture used anywhere

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/entity/test.default.json
I don't think I see default.json used anywhere

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/policy/checkApprovals/2-admin-approval-required.json
> +  "description": "an admin approval is required",
This is TWO admin approvals; update the id/desc to be unique compared to the single approval one

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/policy/checkRateLimit/members-2-transfer-per-day.json
> +      "criterion": "checkRateLimit",
Note: added a card for ensuring undefined historical data won't lead to this criteria permitting. It's a Rego change I believe.
https://linear.app/narval/issue/NAR-1938/checkratelimit-and-checkspendinglimit-should-require-feed

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/policy/set/address-book-and-roles.json
> +      }
Just clarifying: `checkDestinationid` will require that account to be in the address book, right?
Whereas `checkDestinationAddress` + `checkintentChainId` would allow an arbitrary address not in the address book

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/resource/policy/set/approvals-and-spending-limit.json
> +            "tokens": ["eip155:1/slip44:60"]
What happens if no token is filtering here? WIll it accumulate per-token still, or will we get unexpected behavior?

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/lib/__test__/e2e/scenarii/address-book-management.spec.ts
> +  it('bob can transfer from account A to account B', async () => {
This test is failing when I run it

2024-09-17 21:41 UTC, mattschoch commented on packages/armory-sdk/src/lib/__test__/e2e/scenarii/defi-interactions.spec.ts
> +  it('anyone can sign a transfer from a uniswap trader account to a treasury account', async () => {
This test is failing when I run it

2024-09-18 12:45 UTC, Ptroger commented on packages/policy-engine-shared/src/lib/dev.fixture.ts
> +  Antoine: '0x3e4989d1d83959d9dbec1f14bfb0685cfd15f4fd5037dc6e37e88e01838aef65',
🤦 Didn't noticed this

2024-09-18 12:48 UTC, Ptroger commented on packages/armory-sdk/src/resource/entity/fixture.json
Renaming mistake

2024-09-18 12:48 UTC, Ptroger commented on packages/armory-sdk/src/resource/entity/test.default.json
Renaming mistake

2024-09-19 12:09 UTC, Ptroger commented on packages/armory-sdk/src/lib/__test__/e2e/scenarii/defi-interactions.spec.ts
> +  it('anyone can sign a transfer from a uniswap trader account to a treasury account', async () => {
Yes it is normal, I left the test but feature is not there yet. This test will pass when we have a way to check destination groups.
I'm removing it, and re-adding it with checkDestinationGroup criterion later.

2024-09-19 12:09 UTC, Ptroger commented on packages/armory-sdk/src/lib/__test__/e2e/scenarii/address-book-management.spec.ts
> +  it('bob can transfer from account A to account B', async () => {
Fixed it, it was a casing issue.

2024-09-19 12:29 UTC, Ptroger commented on packages/armory-sdk/src/resource/policy/set/approvals-and-spending-limit.json
> +            "tokens": ["eip155:1/slip44:60"]
It won't accumulate per token, but it's not unexpected behavior either.

The default behavior of spending limit is a policy without 'currency' or 'filters.token'.
In this default setup, without filters or currency, we accumulate arbitrary values. And the accumulation of these values is tested against a limit.
That means you are saying: 'don't spend more than 10' without specifying 10 what.
In this circumstances, if you already transfered 5 matic and 2 eth, and now you are trying to transfer 4 unim, it would fail.

The way to have a spending limit over USD is by providing `fiat:usd` as the 'currency' argument. But that would require price feed to be enabled, and we don't have that for now.

Now there is a secondary option to give sense to the limit, which is filtering by the token that was spent. You could be filtering by both MATIC and ETH. In what case the limit would be checked against aggregated MATIC and ETH transfer values.
The reason why I chose to filter by ETH, is because I think filtering by 1 token is the only way we can provide meaningful limits right now.

So to answer your question, removing this token filtering would generate a behavior where any token transfer would be aggregated against the limit.

2024-09-19 12:30 UTC, Ptroger commented on packages/armory-sdk/src/resource/policy/set/approvals-and-spending-limit.json
> +            "tokens": ["eip155:1/slip44:60"]
I have added a rule that allow a member to do any transfer, and a test case to make clear that no other spending is counted against the limit for eth spending

2024-09-19 12:30 UTC, Ptroger commented on packages/armory-sdk/src/resource/policy/set/address-book-and-roles.json
> +      }
Yes exactly

2024-09-19 12:34 UTC, Ptroger commented on packages/armory-sdk/src/resource/entity/default.json
> +  ],
Yes that is true. I delete that

2024-09-19 12:44 UTC, Ptroger commented on packages/armory-sdk/src/resource/policy/checkApprovals/2-admin-approval-required.json
> +  "description": "an admin approval is required",
Done

2024-09-27 16:00 UTC, merged