changed source and destination building
narval-xyz/armory pull request #542
Opened 2024-09-18 12:35 UTC by Ptroger

2024-09-18 14:45 UTC, mattschoch requested changes

2024-09-18 14:45 UTC, mattschoch commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +	print("accountData: ", accountData, "\n")
Probably delete the `print` statements?

2024-09-18 14:45 UTC, mattschoch commented on apps/policy-engine/src/resource/open-policy-agent/rego/__test__/criteria/intent/source_test.rego
> +	checkSourceId({"eip155:137:0xddcf208f219a6e6af072f2cfdc615b2c1805f98e"}) with input as requestWithEip1559Transaction with data.entities as entities
Why'd you remove the `res` match in this test?

I added it back & _the test fails_.

```

	res == {
		"id": "eip155:137:0xddcf208f219a6e6af072f2cfdc615b2c1805f98e",
		"address": "0xddcf208f219a6e6af072f2cfdc615b2c1805f98e",
		"chainId": 137,
		"classification": "managed",
		"accountType": "eoa",
		"assignees": ["test-bob-uid", "test-alice-uid", "test-foo-uid", "test-bar-uid"],
		"accountGroups": {"test-account-group-one-uid"},
	}
```

The reason is that the test data is using `"account"` as the classification. I'll push this fix.

2024-09-18 14:45 UTC, mattschoch commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +	chainId = chainAccount.chainId
Why'd you change `:=` to `=`? This is an assignment, so i believe `:=` is appropriate.

Also applies to the other version of this assignment

2024-09-18 14:46 UTC, mattschoch commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +	print("accountData: ", accountData, "\n")
I pushed this change

2024-09-18 14:46 UTC, mattschoch commented on apps/policy-engine/src/resource/open-policy-agent/rego/__test__/criteria/intent/source_test.rego
> +	checkSourceId({"eip155:137:0xddcf208f219a6e6af072f2cfdc615b2c1805f98e"}) with input as requestWithEip1559Transaction with data.entities as entities
I pushed this fix

2024-09-19 08:34 UTC, Ptroger commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +	chainId = chainAccount.chainId
For consistency: `:=` was not really used.

2024-09-26 13:46 UTC, wcalderipe commented on apps/policy-engine/src/resource/open-policy-agent/rego/__test__/criteria/intent/source_test.rego
> +	enti = object.union(
```suggestion
	test_input = object.union(requestWithEip1559Transaction, {"intent": object.union(requestWithEip1559Transaction.intent, {"from": "eip155:137:0x2227be636c3ad8cf9d08ba8bdba4abd2ef29bd23"})})
	test_entities = object.union(
```

Don't rename them to something else because the name carries meaning.

2024-09-26 13:47 UTC, wcalderipe commented on apps/policy-engine/src/resource/open-policy-agent/rego/__test__/criteria/intent/source_test.rego
> +	checkSourceClassification({"internal"}) with input as req with data.entities as enti
Where's the assertion?

2024-09-26 13:50 UTC, wcalderipe commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +		# TODO: @ptroger add addressBookGroups when implemented
What about this TODO?

2024-09-27 09:02 UTC, Ptroger commented on apps/policy-engine/src/resource/open-policy-agent/rego/util/account.rego
> +		# TODO: @ptroger add addressBookGroups when implemented
Not implemented yet

2024-09-27 12:53 UTC, mattschoch approved these changes

2024-09-27 14:59 UTC, merged